"""
Goal-Oriented Autonomous Controller (GOAC) for rocket mission management.

The GOAC is the top-level deliberative layer of the mission management
subsystem.  It accepts high-level mission goals, decomposes them via the
HTN planner, dispatches them through the reactive executive, and uses
the Utility Accrual scheduler for resource allocation -- all inside a
closed-loop architecture::

    goal -> plan -> schedule -> execute -> monitor -> replan if needed

The controller continuously steps through the loop, reacting to
anomalies, updating goals, and adjusting plans as the world state
evolves during flight.

References:
    ESA GOAC -- "Goal Oriented Autonomous Controller for Space Missions"
    Ingrand & Ghallab -- "Deliberation for Autonomous Robots: A Survey" (2017)
    NASA Europa Clipper -- Onboard Planning & Execution Architecture
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any, Dict, List, Optional, Tuple

from rocket_ai_os.config import MissionPhase

from rocket_ai_os.mission.planner import (
    HTNPlanner,
    PlanningError,
    PrimitiveTask,
    TaskStatus,
)
from rocket_ai_os.mission.executive import (
    Executive,
    ExecutionResult,
    ExecutionStatus,
    FaultInfo,
    TaskOutcome,
)
from rocket_ai_os.mission.scheduler import (
    CurveType,
    SchedulableTask,
    ScheduleEntry,
    UASScheduler,
    UtilityFunction,
)

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------

class GOACState(Enum):
    """Top-level state of the GOAC controller."""
    IDLE = auto()
    PLANNING = auto()
    SCHEDULING = auto()
    EXECUTING = auto()
    MONITORING = auto()
    REPLANNING = auto()
    ANOMALY_RESPONSE = auto()
    MISSION_COMPLETE = auto()
    ABORTED = auto()


class GoalStatus(Enum):
    """Lifecycle status of a mission goal."""
    PENDING = auto()
    ACTIVE = auto()
    ACHIEVED = auto()
    FAILED = auto()
    SUPERSEDED = auto()


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Goal:
    """
    A high-level mission goal that the GOAC pursues.

    Attributes:
        name:         Human-readable goal identifier.
        priority:     Numeric priority (lower = higher priority).
        target_state: Dict of world-state predicates that define success.
                      Keys are state variable names; values are the
                      required values after the goal is achieved.
        constraints:  Dict of constraints that must hold during pursuit
                      (e.g. ``{"fuel_remaining": lambda f: f > 0.05}``).
        utility:      Scalar utility gained by achieving this goal.
        status:       Current lifecycle status.
        plan:         Primitive-task plan generated by the HTN planner.
    """
    name: str
    priority: int = 5
    target_state: Dict[str, Any] = field(default_factory=dict)
    constraints: Dict[str, Any] = field(default_factory=dict)
    utility: float = 1.0
    status: GoalStatus = GoalStatus.PENDING
    plan: List[PrimitiveTask] = field(default_factory=list)

    def is_achieved(self, world_state: Dict[str, Any]) -> bool:
        """
        Return True if every predicate in *target_state* is satisfied
        by *world_state*.
        """
        for key, required in self.target_state.items():
            actual = world_state.get(key)
            if callable(required):
                if not required(actual):
                    return False
            elif actual != required:
                return False
        return True

    def constraints_satisfied(self, world_state: Dict[str, Any]) -> bool:
        """
        Return True if all constraints hold in *world_state*.
        """
        for key, constraint in self.constraints.items():
            actual = world_state.get(key)
            if callable(constraint):
                if not constraint(actual):
                    return False
            elif actual != constraint:
                return False
        return True


@dataclass
class WorldState:
    """
    Snapshot of the vehicle and environment state consumed by the GOAC.

    All fields are also accessible as a flat dict via :meth:`to_dict` so
    that the planner and executive can work with plain key-value state
    representations.

    Attributes:
        vehicle_state:    Dict of vehicle dynamic state (position, velocity,
                          attitude, etc.).
        subsystem_health: Dict mapping subsystem name -> health flag.
        fuel_remaining:   Fraction of propellant remaining [0.0, 1.0].
        comms_status:     Communication link status string.
        phase:            Current :class:`MissionPhase`.
        extra:            Arbitrary additional state variables.
    """
    vehicle_state: Dict[str, Any] = field(default_factory=dict)
    subsystem_health: Dict[str, bool] = field(default_factory=dict)
    fuel_remaining: float = 1.0
    comms_status: str = "nominal"
    phase: MissionPhase = MissionPhase.PRE_LAUNCH
    extra: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Flatten every field into a single dict for planner consumption."""
        flat: Dict[str, Any] = {}
        flat.update(self.vehicle_state)
        flat["subsystem_health"] = dict(self.subsystem_health)
        flat["fuel_remaining"] = self.fuel_remaining
        flat["comms_status"] = self.comms_status
        flat["phase"] = self.phase
        flat.update(self.extra)
        return flat


# ---------------------------------------------------------------------------
# GOAC Controller
# ---------------------------------------------------------------------------

class GOAC:
    """
    Goal-Oriented Autonomous Controller.

    Orchestrates the HTN planner, reactive executive and UA scheduler
    in a closed-loop goal-plan-execute-monitor cycle.

    Parameters:
        planner:   HTN planner instance (created internally if *None*).
        executive: Reactive executive instance (created internally if *None*).
        scheduler: UA scheduler instance (created internally if *None*).
        max_replan_per_goal: Maximum replanning attempts for a single goal.

    Usage::

        goac = GOAC()
        goac.set_goal(Goal(
            name="achieve_orbit_insertion",
            target_state={"phase": MissionPhase.COAST},
            utility=100.0,
        ))
        while goac.state != GOACState.MISSION_COMPLETE:
            actions = goac.step(world_state)
            # execute actions in the simulation
    """

    def __init__(
        self,
        planner: Optional[HTNPlanner] = None,
        executive: Optional[Executive] = None,
        scheduler: Optional[UASScheduler] = None,
        max_replan_per_goal: int = 3,
    ) -> None:
        self._planner = planner or HTNPlanner()
        self._executive = executive or Executive(planner=self._planner)
        self._scheduler = scheduler or UASScheduler()

        self._state: GOACState = GOACState.IDLE
        self._goals: List[Goal] = []
        self._active_goal: Optional[Goal] = None
        self._pending_plan: List[PrimitiveTask] = []
        self._plan_index: int = 0
        self._max_replan = max_replan_per_goal
        self._replan_count: int = 0
        self._anomaly_queue: List[FaultInfo] = []

        # History / statistics
        self._goals_achieved: int = 0
        self._goals_failed: int = 0
        self._total_actions_executed: int = 0
        self._step_count: int = 0

        logger.info("GOAC initialised  max_replan_per_goal=%d", max_replan_per_goal)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def state(self) -> GOACState:
        """Current GOAC state-machine state."""
        return self._state

    @property
    def active_goal(self) -> Optional[Goal]:
        """The currently pursued goal, or None."""
        return self._active_goal

    @property
    def goals(self) -> List[Goal]:
        """All registered goals (active, pending, achieved, failed)."""
        return list(self._goals)

    # ------------------------------------------------------------------
    # Goal management
    # ------------------------------------------------------------------

    def set_goal(self, goal: Goal) -> None:
        """
        Register a new mission goal.

        The goal is added to the goal queue and will be pursued in
        priority order when :meth:`step` is called.  If no goal is
        currently active the controller transitions to PLANNING on the
        next step.

        Args:
            goal: The mission goal to pursue.
        """
        goal.status = GoalStatus.PENDING
        self._goals.append(goal)
        self._goals.sort(key=lambda g: g.priority)
        logger.info(
            "Goal '%s' registered  priority=%d  utility=%.1f",
            goal.name,
            goal.priority,
            goal.utility,
        )

    def remove_goal(self, goal_name: str) -> bool:
        """
        Remove a goal by name.  Returns True if found and removed.

        If the removed goal is the currently active goal the controller
        transitions to IDLE (or picks the next goal on the next step).
        """
        for i, goal in enumerate(self._goals):
            if goal.name == goal_name:
                removed = self._goals.pop(i)
                removed.status = GoalStatus.SUPERSEDED
                if self._active_goal is removed:
                    self._active_goal = None
                    self._pending_plan.clear()
                    self._state = GOACState.IDLE
                logger.info("Goal '%s' removed (superseded)", goal_name)
                return True
        return False

    # ------------------------------------------------------------------
    # Main step loop
    # ------------------------------------------------------------------

    def step(self, world_state: WorldState) -> List[PrimitiveTask]:
        """
        Advance the GOAC by one deliberation cycle.

        This is the main entry point called once per major frame.  It
        returns a (possibly empty) list of primitive tasks that should
        be executed by the caller or by the executive.

        The step performs different work depending on the current state:

        * **IDLE** -- select the highest-priority pending goal and
          transition to PLANNING.
        * **PLANNING** -- decompose the active goal via the HTN planner.
        * **SCHEDULING** -- pass the plan through the UA scheduler.
        * **EXECUTING** -- dispatch the next primitive task.
        * **MONITORING** -- check whether the active goal has been
          achieved or a constraint has been violated.
        * **REPLANNING** -- generate a new plan after a failure.
        * **ANOMALY_RESPONSE** -- handle queued anomalies.

        Args:
            world_state: Current vehicle/environment state.

        Returns:
            List of primitive tasks dispatched this step (0 or 1 tasks
            in the common case).
        """
        self._step_count += 1
        ws_dict = world_state.to_dict()
        actions: List[PrimitiveTask] = []

        # Process any queued anomalies first
        if self._anomaly_queue and self._state not in (
            GOACState.ABORTED,
            GOACState.ANOMALY_RESPONSE,
        ):
            self._state = GOACState.ANOMALY_RESPONSE

        # --- State machine dispatch ------------------------------------

        if self._state == GOACState.IDLE:
            self._step_idle(ws_dict)

        elif self._state == GOACState.PLANNING:
            self._step_planning(ws_dict)

        elif self._state == GOACState.SCHEDULING:
            self._step_scheduling(ws_dict)

        elif self._state == GOACState.EXECUTING:
            actions = self._step_executing(ws_dict)

        elif self._state == GOACState.MONITORING:
            self._step_monitoring(ws_dict)

        elif self._state == GOACState.REPLANNING:
            self._step_replanning(ws_dict)

        elif self._state == GOACState.ANOMALY_RESPONSE:
            actions = self._step_anomaly_response(ws_dict)

        elif self._state in (GOACState.MISSION_COMPLETE, GOACState.ABORTED):
            pass  # terminal states

        return actions

    # ------------------------------------------------------------------
    # State handlers
    # ------------------------------------------------------------------

    def _step_idle(self, ws: Dict[str, Any]) -> None:
        """Select the next pending goal, or declare mission complete."""
        pending = [
            g for g in self._goals if g.status == GoalStatus.PENDING
        ]
        if not pending:
            # Check if all goals are achieved
            all_achieved = all(
                g.status == GoalStatus.ACHIEVED for g in self._goals
            )
            if self._goals and all_achieved:
                self._state = GOACState.MISSION_COMPLETE
                logger.info("All goals achieved -- mission complete")
            # Otherwise stay IDLE (waiting for new goals)
            return

        # Pick highest-priority pending goal
        self._active_goal = pending[0]
        self._active_goal.status = GoalStatus.ACTIVE
        self._replan_count = 0
        self._state = GOACState.PLANNING
        logger.info(
            "Selected goal '%s' (priority=%d)",
            self._active_goal.name,
            self._active_goal.priority,
        )

    def _step_planning(self, ws: Dict[str, Any]) -> None:
        """Decompose the active goal into a primitive-task plan."""
        if self._active_goal is None:
            self._state = GOACState.IDLE
            return

        goal = self._active_goal
        try:
            plan = self._planner.plan(goal.name, ws)
            goal.plan = plan
            self._pending_plan = list(plan)
            self._plan_index = 0
            self._state = GOACState.SCHEDULING
            logger.info(
                "Plan for '%s': %d tasks (est. %.1fs)",
                goal.name,
                len(plan),
                self._planner.estimate_plan_duration(plan),
            )
        except PlanningError as exc:
            logger.error("Planning failed for '%s': %s", goal.name, exc)
            self._replan_count += 1
            if self._replan_count > self._max_replan:
                goal.status = GoalStatus.FAILED
                self._goals_failed += 1
                self._active_goal = None
                self._state = GOACState.IDLE
                logger.error(
                    "Goal '%s' failed after %d plan attempts",
                    goal.name,
                    self._replan_count,
                )
            else:
                # Stay in PLANNING to retry next step
                pass

    def _step_scheduling(self, ws: Dict[str, Any]) -> None:
        """
        Pass the plan through the UA scheduler for resource allocation.

        This converts each :class:`PrimitiveTask` into a
        :class:`SchedulableTask`, schedules them, and reorders the
        execution plan according to the schedule.
        """
        if not self._pending_plan:
            self._state = GOACState.EXECUTING
            return

        schedulable_tasks: List[SchedulableTask] = []
        current_time = time.monotonic()

        for i, ptask in enumerate(self._pending_plan):
            st = SchedulableTask(
                name=ptask.name,
                utility_function=UtilityFunction(
                    curve_type=CurveType.STEP,
                    base_value=10.0 / max(ptask.criticality, 1),
                ),
                resource_requirements={"cpu": 0.1},
                deadline=current_time + 600.0,  # 10-minute horizon
                duration=ptask.duration_estimate,
                priority=ptask.criticality,
            )
            schedulable_tasks.append(st)

        schedule = self._scheduler.schedule(
            schedulable_tasks,
            current_time=current_time,
        )

        # Reorder the pending plan to match the schedule
        name_to_task = {t.name: t for t in self._pending_plan}
        reordered: List[PrimitiveTask] = []
        for entry in schedule:
            task = name_to_task.get(entry.task.name)
            if task is not None:
                reordered.append(task)

        # Append any tasks that were not scheduled (they stay at the end)
        scheduled_names = {e.task.name for e in schedule}
        for task in self._pending_plan:
            if task.name not in scheduled_names:
                reordered.append(task)

        self._pending_plan = reordered
        self._plan_index = 0
        self._state = GOACState.EXECUTING
        logger.info("Scheduling complete -- transitioning to EXECUTING")

    def _step_executing(self, ws: Dict[str, Any]) -> List[PrimitiveTask]:
        """Dispatch the next primitive task in the plan."""
        if self._plan_index >= len(self._pending_plan):
            # Plan exhausted -- check if goal is achieved
            self._state = GOACState.MONITORING
            return []

        task = self._pending_plan[self._plan_index]
        logger.info(
            "Executing task %d/%d: '%s'",
            self._plan_index + 1,
            len(self._pending_plan),
            task.name,
        )

        result = self._executive.dispatch(task, ws)
        self._total_actions_executed += 1

        if result.outcome == TaskOutcome.SUCCESS:
            self._plan_index += 1
            # Stay in EXECUTING for the next step
            return [task]
        else:
            # Failure -- transition to replanning
            logger.warning(
                "Task '%s' failed (%s) -- transitioning to REPLANNING",
                task.name,
                result.outcome.name,
            )
            self._state = GOACState.REPLANNING
            return [task]

    def _step_monitoring(self, ws: Dict[str, Any]) -> None:
        """
        Check if the active goal has been achieved, or if constraints
        have been violated.
        """
        if self._active_goal is None:
            self._state = GOACState.IDLE
            return

        goal = self._active_goal

        if goal.is_achieved(ws):
            goal.status = GoalStatus.ACHIEVED
            self._goals_achieved += 1
            self._active_goal = None
            self._pending_plan.clear()
            self._state = GOACState.IDLE
            logger.info("Goal '%s' ACHIEVED", goal.name)
            return

        if not goal.constraints_satisfied(ws):
            logger.warning(
                "Constraints violated for goal '%s' -- replanning",
                goal.name,
            )
            self._state = GOACState.REPLANNING
            return

        # Plan is exhausted but goal not yet achieved -- replan
        if self._plan_index >= len(self._pending_plan):
            logger.info(
                "Plan exhausted but goal '%s' not achieved -- replanning",
                goal.name,
            )
            self._state = GOACState.REPLANNING

    def _step_replanning(self, ws: Dict[str, Any]) -> None:
        """Attempt to generate a new plan for the active goal."""
        if self._active_goal is None:
            self._state = GOACState.IDLE
            return

        self._replan_count += 1
        goal = self._active_goal

        if self._replan_count > self._max_replan:
            goal.status = GoalStatus.FAILED
            self._goals_failed += 1
            self._active_goal = None
            self._pending_plan.clear()
            self._state = GOACState.IDLE
            logger.error(
                "Goal '%s' FAILED after %d replan attempts",
                goal.name,
                self._replan_count,
            )
            return

        logger.info(
            "Replanning for goal '%s' (attempt %d/%d)",
            goal.name,
            self._replan_count,
            self._max_replan,
        )

        # If there was a specific failed task, use the planner's replan
        failed_tasks = [
            t for t in self._pending_plan
            if t.status == TaskStatus.FAILED
        ]
        if failed_tasks:
            recovery_plan = self._planner.replan(failed_tasks[-1], ws)
            remaining = self._pending_plan[self._plan_index + 1:]
            self._pending_plan = recovery_plan + remaining
        else:
            # Full replan
            try:
                self._pending_plan = self._planner.plan(goal.name, ws)
            except PlanningError as exc:
                logger.error("Full replan failed: %s", exc)
                goal.status = GoalStatus.FAILED
                self._goals_failed += 1
                self._active_goal = None
                self._pending_plan.clear()
                self._state = GOACState.IDLE
                return

        self._plan_index = 0
        self._state = GOACState.SCHEDULING

    def _step_anomaly_response(
        self,
        ws: Dict[str, Any],
    ) -> List[PrimitiveTask]:
        """Process queued anomalies and determine response actions."""
        actions: List[PrimitiveTask] = []

        while self._anomaly_queue:
            fault = self._anomaly_queue.pop(0)
            logger.warning(
                "Processing anomaly: type=%s  severity=%d  subsystem=%s",
                fault.fault_type,
                fault.severity,
                fault.subsystem,
            )

            response_tasks = self._determine_anomaly_response(fault, ws)
            actions.extend(response_tasks)

            # Execute response tasks immediately
            for task in response_tasks:
                self._executive.dispatch(task, ws)
                self._total_actions_executed += 1

        # Return to previous state or trigger replan
        if self._active_goal is not None:
            self._state = GOACState.REPLANNING
        else:
            self._state = GOACState.IDLE

        return actions

    # ------------------------------------------------------------------
    # Anomaly handling
    # ------------------------------------------------------------------

    def handle_anomaly(self, fault: FaultInfo) -> str:
        """
        Accept an external anomaly notification.

        The fault is queued and will be processed on the next :meth:`step`
        call.  Severity-1 faults trigger an immediate state transition to
        ANOMALY_RESPONSE.

        Args:
            fault: Fault information descriptor.

        Returns:
            String describing the immediate response taken.
        """
        self._anomaly_queue.append(fault)
        logger.warning(
            "Anomaly queued: type=%s  severity=%d",
            fault.fault_type,
            fault.severity,
        )

        if fault.severity <= 1:
            # Critical fault -- immediate response
            self._state = GOACState.ANOMALY_RESPONSE
            return f"CRITICAL anomaly '{fault.fault_type}' -- immediate response"

        return f"Anomaly '{fault.fault_type}' queued for next step"

    def _determine_anomaly_response(
        self,
        fault: FaultInfo,
        ws: Dict[str, Any],
    ) -> List[PrimitiveTask]:
        """
        Map a fault to a list of response tasks.

        This is a rule-based approach; in a full system it would consult
        a fault-response database or learned model.
        """
        responses: List[PrimitiveTask] = []

        if fault.severity <= 1:
            # Critical -- immediate safe mode
            responses.append(PrimitiveTask(
                name="emergency_safe_mode",
                preconditions={},
                effects={"safe_mode": True},
                duration_estimate=1.0,
                criticality=1,
            ))
            if ws.get("engines_running", False):
                responses.append(PrimitiveTask(
                    name="emergency_engine_shutdown",
                    preconditions={},
                    effects={"engines_running": False, "thrust": 0.0},
                    duration_estimate=0.5,
                    criticality=1,
                ))

        elif fault.severity == 2:
            # High -- reduce operational tempo
            responses.append(PrimitiveTask(
                name="enter_reduced_mode",
                preconditions={},
                effects={"reduced_mode": True},
                duration_estimate=0.5,
                criticality=2,
            ))

        elif fault.severity == 3:
            # Medium -- diagnostic task
            responses.append(PrimitiveTask(
                name="run_subsystem_diagnostic",
                preconditions={},
                effects={"diagnostic_complete": True},
                duration_estimate=3.0,
                criticality=3,
                parameters={"subsystem": fault.subsystem},
            ))

        else:
            # Low severity -- log and continue
            responses.append(PrimitiveTask(
                name="log_anomaly",
                preconditions={},
                effects={"anomaly_logged": True},
                duration_estimate=0.1,
                criticality=5,
                parameters={"fault_type": fault.fault_type},
            ))

        return responses

    # ------------------------------------------------------------------
    # Mission status
    # ------------------------------------------------------------------

    def get_mission_status(self) -> Dict[str, Any]:
        """
        Return a comprehensive summary of the mission state.

        Includes GOAC state, goal statuses, execution stats, and
        planner / executive summaries.
        """
        goal_summary = []
        for g in self._goals:
            goal_summary.append({
                "name": g.name,
                "priority": g.priority,
                "status": g.status.name,
                "utility": g.utility,
                "plan_length": len(g.plan),
            })

        return {
            "goac_state": self._state.name,
            "step_count": self._step_count,
            "active_goal": (
                self._active_goal.name if self._active_goal else None
            ),
            "goals": goal_summary,
            "goals_achieved": self._goals_achieved,
            "goals_failed": self._goals_failed,
            "total_actions_executed": self._total_actions_executed,
            "plan_progress": (
                f"{self._plan_index}/{len(self._pending_plan)}"
                if self._pending_plan else "0/0"
            ),
            "anomalies_pending": len(self._anomaly_queue),
            "executive_summary": self._executive.get_summary(),
            "scheduler_summary": self._scheduler.get_schedule_summary(),
        }

    # ------------------------------------------------------------------
    # Reset / lifecycle
    # ------------------------------------------------------------------

    def reset(self) -> None:
        """Reset the controller to its initial state."""
        self._state = GOACState.IDLE
        self._goals.clear()
        self._active_goal = None
        self._pending_plan.clear()
        self._plan_index = 0
        self._replan_count = 0
        self._anomaly_queue.clear()
        self._goals_achieved = 0
        self._goals_failed = 0
        self._total_actions_executed = 0
        self._step_count = 0
        logger.info("GOAC reset")

    def __repr__(self) -> str:
        return (
            f"<GOAC state={self._state.name} "
            f"goals={len(self._goals)} "
            f"active={self._active_goal.name if self._active_goal else 'none'} "
            f"achieved={self._goals_achieved} failed={self._goals_failed}>"
        )
